### ISSUE TITLE
Add support for "allOf" keyword

### ISSUE THREAD

**Issue by akarzelek** [psrebniak/swagger-typescript-client-generator#14]
eg. for excerpt from attachment I'd expect these generated models: 
`export type BasicMessage = {
preheader: string;
subject: string;
}`

`export type Message = {
preheader: string;
subject: string;
id: number;
}`
[example.zip](https://github.com/psrebniak/swagger-typescript-client-generator/files/3879915/example.zip)

**Comment by piotr-srebniak-limango** [comment]
@akarzelek should work in 1.3.1 version - please bump both `swagger-typescript-client-generator` and `swagger-typescript-client-generator-runtime`

**Comment by psrebniak** [comment]
@akarzelek  should work in 1.3.1 version - please bump both swagger-typescript-client-generator and swagger-typescript-client-generator-runtime

**Comment by psrebniak** [comment]
@akarzelek feel free to reopen if needed
